### PR TITLE
Updating Continuous Integration section

### LINKED ISSUE #31: [Revision] Continuous Integration
Section reserved by Gabriel Lyra.

### PR DESCRIPTION
**Pull request by Gabriel-Lyra**
-Deleted continuousintegration.md file and replaced for continuousintegration.ipynb format
-Added Hands-on (was missing)
-Deleted meaningless paragraph (explaining the same thing a second time)
-Minor layout and content changes
-Minor writing mistakes fixes

**-Updated from previous pull request version taking into account Bruno César critiques**

This closes #31

### CODE REVIEW

**Review by bcgs — COMMENTED** [review]
- Image not found;
- Instead of a video link that opens in another tab you can use something like:
```python
from IPython.display import YouTubeVideo
YouTubeVideo('upzTw3V2Zzs')
```
- Google Colab button centralized is good but everyone is using it aligned to the left, so it breaks the common use;
- The calculator stuff to be honest it's a bit confusing. This kinda notation using exclamation mark doesn't work on terminal, it's more like talking to the Colab integrated Python... I understand what the code does but this is definitely not easy at first glance...

I ran it on Colab and got:
```
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `echo def add(x, y): >> calc.py'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `echo def subtract(x, y): >> calc.py'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `echo def multiply(x, y): >> calc.py'
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `echo def divide(x, y): >> calc.py'
```
It means Colab isn’t working...

I’d go with simple Python code, like so:
_"Suppose you have a basic calculator.... bla bla bla..."_
```python
def add(x, y):
    return x + y
```
_"Now, commit the code... bla bla bla"_
- Found some typos but nothing much, can be done later;
- Maybe some references if you have...

**Comment by Gabriel-Lyra** [comment]
-Fixed image not appearing
-Aligned colab badge
-Changed code into simple python code
-Change video visualization format

**Review by bcgs — COMMENTED** [review]
Gabriel, the Colab's button won't work because it's pointing to a non-existing notebook (**ANOTHER_NOTEBOOK.ipynb**). Marcelo said he won't be happy the Colab content being the same as of its chapter. 

The main code is way better but I'd still break it down into 5 cells or so, but it's ok... just something you can change later but don't forget the button. 🥳

**Comment by bcgs** [comment]
Desculpa ai Gabriel mas desconsidere minhas opiniões pq já não sei mais o que Marcelo quer, talvez outra pessoa consiga te ajudar melhor na revisão.

**Comment by Gabriel-Lyra** [comment]
Eu vi as conversas no classroom. Relaxa, ao meu ver o próprio dAmorim não
sabe o que quer, ou se sabe não está explicitando de forma categórica. É
muito difícil trabalhar em uma normalização quando existe muita fluidez
assim.

**Comment by damorim** [comment]
Está muito melhor comparado ao que era antes.

Comentários:

* Coloque o widget do vídeo na página.

* Use a mesma tecnologia usada no vídeo no exemplo. O vídeo ilustrou (rapidamente) como usar GitHub Actions para automatizar CI/CD. Use também GitHub Action (até porque estamos usando isto no nosso livro) **no exemplo**. 

* Demonstre realmente a execução do workflow CI/CD no seu exemplo no Jupyter notebook. Crie um repositório com (código simple e teste) para isto, se necessário.

**Pull request merged**
