### PR TITLE
Updating Unit Testing section

### LINKED ISSUE #35: [Revision] Unit Testing

### PR DESCRIPTION
**Pull request by bcgs**
- Content refactored
- New files (notebooks) of examples added

This closes #35

### CODE REVIEW

**Review by pedroqueiroga — COMMENTED** [review]
Pretty neat. It is better organized now. I'm not sure if there should be more than one `Hands on` section, though. 

Marcelo said at some point that he didn't understand the need for the subchapter `Organization of unit tests`, and now with your changes it seems even less needed, since there is so little there. The filename is also not the same as the header, which is now `Organization of Test Cases`.

Isn't the 8-min video too long? And perhaps it should be in the main section. I feel like a video inside a hands on collab is not well placed, but perhaps it is.

I liked the little footer with further informations, but I think throughout the book this would be in a section called References, and perhaps in the main section instead of on hands on collabs. Also, I think Hands-On should actually be Hands On, since it is how it was used throughtout the book.

**Comment by bcgs** [comment]
Took in account everything you said @pedroqueiroga. Just wrapped everything in a single file and made more modifications based on what was seen early today in the class.

**Comment by bcgs** [comment]
I think it is sufficiently good to be merged, at least better than the older version. If there is something missing I'll prolly do other PR's.

**Review by pedroqueiroga — COMMENTED** [review]
Looks better now, indeed. I see that you removed all the extra examples and chose to focus on just one, which I think will be preferred by Marcelo, too. Neat.

**Pull request merged**
